/** UI primitives barrel: `import { Card, Badge, Button } from '@/components/ui';` — see docs/COMPONENTS.md. */
export { AnimatedNumber } from './AnimatedNumber';
export { Avatar, AvatarStack } from './Avatar';
export type { AvatarPerson } from './Avatar';
export { Badge, Pill } from './Badge';
export { Button, buttonClasses } from './Button';
export { Callout } from './Callout';
export { Card } from './Card';
export { DataList } from './DataList';
export type { DataColumn } from './DataList';
export { DotScale } from './DotScale';
export { EmptyState } from './EmptyState';
export { EnergyClassBadge } from './EnergyClassBadge';
export { FilterChips } from './FilterChips';
export type { FilterChipOption } from './FilterChips';
export { HealthBadge } from './HealthBadge';
export { IconButton } from './IconButton';
export { KeyValue } from './KeyValue';
export type { KeyValueItem } from './KeyValue';
export { Modal } from './Modal';
export { PageHeader } from './PageHeader';
export { PhasePill } from './PhasePill';
export { ProgressBar } from './ProgressBar';
export { RangeBar } from './RangeBar';
export { SearchInput } from './SearchInput';
export { SectionHeader } from './SectionHeader';
export { Segmented } from './Segmented';
export type { SegmentedOption } from './Segmented';
export { Select } from './Select';
export type { SelectOption } from './Select';
export { Sheet } from './Sheet';
export { Skeleton } from './Skeleton';
export { Slider } from './Slider';
export { Stat } from './Stat';
export { StatusDot } from './StatusDot';
export { RouteTabs, Tabs } from './Tabs';
export type { RouteTabItem, TabItem } from './Tabs';
export { Toggle } from './Toggle';
export { Tooltip } from './Tooltip';
export { useMediaQuery } from './useMediaQuery';
export { SERIES_COLORS, seriesColor, TONE_CLASSES, toneVar } from './tone';
